Redishelm
maykinmedia/commonground-ansible pull request #22
Opened 2022-12-28 12:44 UTC by sjoerdie

Some components require Redis AOF persistence enabled:

Switched the entire redis deployment to use [Bitnami package for Redis(R)
](https://github.com/bitnami/charts/tree/main/bitnami/redis)

[AOF](https://github.com/bitnami/charts/blob/main/bitnami/redis/values.yaml#:~:text=%23%23-,commonConfiguration,-%3A%20%7C%2D) is enabled by default. 

Most (if not all) feature requirements (e.g., persistence volumes, existing configmaps, HA requirements, etc) are available in the chart. All values from the chart can be used in the role by setting them in the `django_app_k8s_redis_helm_values` variable.

Deployement was tested on an AKS cluster and works as intended.

2023-01-03 08:48 UTC, sergei-maertens requested changes

2023-01-03 08:48 UTC, sergei-maertens commented on roles/django_app_k8s/tasks/deployments.yml
> +    repo_url: "https://charts.bitnami.com/bitnami"
shouldn't this be properly versioned? I see they're up to major version 17 already in the bitnami chart.

2023-01-03 08:48 UTC, sergei-maertens commented on roles/django_app_k8s/README.md
> +  node) to deploy some components
Shouldn't we also specify the `kubernetes` collection in our own dependencies? https://github.com/maykinmedia/commonground-ansible/blob/main/galaxy.yml#L45

2023-06-27 10:07 UTC, SilviaAmAm commented
Discussed with Sjoerd:
We will no longer use ansible to deploy for DH so this can be closed.

2023-06-27 10:07 UTC, closed without merging